package com.evnit.ttpm.AuthApp.model.device.ti;

import lombok.Data;

import javax.persistence.Column;
import java.util.Date;
@Data
public class DeviceTIDetailDto {
    private String assetId;
    private String assetIdParent;
    private String assetDesc;
    private String idCuon;
    private Integer assetORD;
    private String categoryId;
    private String typeId;
    private String useStatusLastId;
    private String useStatusLastIdStr;
    private Date useStatusLastDTime;
    private String serialNum;
    private String pManufacturerId;
    private String pManufacturerIdStr;
    private String nationalFact;
    private Date pInstallDate;
    private String userCRId;
    private Date userCRDTime;
    private String userMDFId;
    private Date userMDFDTime;
    private String orgId;
    private String uLevelId;
    private String assetNote;
    private Date dateOperation;
    private String assetIdLink;
    private Date dateAccreditation;
    private Date inspectionStamps;
    private Double cycleAccreditation;
    private String cycleAccreditationStr;
    private String attrDataId;
    private String objTypeId;
    private String objId;
    private String cuon;
    private String pha;
    private String idDiemDo;
    private String congTo;
    private Date pDuyetMau;
    private String kieuTI;
    private String areaId;
    private String areaName;
    private String powerSystemName;
    private String nameTUCuon;
    private String powerSystemType;
    private Integer ownershipUnit;
    private String ownershipUnitStr;
    private String dvsh;
    private Boolean xnk;
    private Integer statusTU;
    private String statusTUStr;
    private String tinhChat;
    private Date dateAccreditationNext;
    private String diemDoName;
    private String machNThu;
    private String cuonDNoi;
    private String tsb;
    private String ccx;
    private String dungLuong;
    private String powerSystemStatus;
    private String powerSystemStatusStr;
    private String powerSystemId;
    private Integer countTB;
    private Integer countBoTB;
    private Integer assetOrd;
    private Integer typeNumber;
}
